### ISSUE TITLE
datapath model

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#36]
1 verify datapath model  with calico  cilium macvlan

2 update datapath designe markdown

3 tcp udp  websocket

**Comment by dcwbq** [comment]
1、calico overlay mode is fine, but 'kubectl set env daemonset -n kube-system calico-node FELIX_CHAININSERTMODE=Append' needs to be set

2、When the macvlan is used, the destCIDR packet must be forwarded to the host; otherwise, the rule cannot be matched

3、cilium does not work, on the EgressGatewayNode, cilium does not do SNAT for traffic coming from Pods on other nodes

**Comment by dcwbq** [comment]
2 update datapath designe markdown
![Egress-Gateway](https://user-images.githubusercontent.com/62228454/209753491-fe48ec33-8fa2-45e6-bc19-1b88b00e171c.jpg)

**Comment by dcwbq** [comment]
cilium  在网关节点即使补齐了 SNAT 的规则，但还是不通

三次握手  前两个包都没问题   最后一个 ACK 的包  不知道为什么没有走 Egress 隧道  
而且抓包看到  直接从物理网卡走出去了  也没有做SNAT

SYN+ACK 的包 网关节点回给Pod 时，也不是走的 Egress 隧道，而是cilium  自己的隧道

**Comment by dcwbq** [comment]
![企业微信截图_69d5adfb-2842-473b-9071-d814df5e6fc4](https://user-images.githubusercontent.com/62228454/230302266-a8e8d20a-6169-403d-ac9d-ad56382ff20e.png)
